name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js@latest
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
          cache: 'npm'
      - run: npm ci
      - name: Build
        run: npm run build

  start:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - run: pm2 restart all
      - run: sudo service nginx restart